### ISSUE TITLE
AttributeError: module 'pyfoal' has no attribute 'align'

### ISSUE THREAD

**Issue by KalvinThien** [MJP1998/Auto_short_generator#3]
File "d:\tool_tao_video\AI\src\video_generator.py", line 240, in generate_video
final_clip = self.overlay_subtitles(final_clip, get_alignement(script_without_emojis, audio_object), script,
File "d:\tool_tao_video\AI\src\video_generator.py", line 56, in get_alignement
return pyfoal.align(text, audio_object.get_audio_np_array(), audio_object.get_sample_rate()).json()
AttributeError: module 'pyfoal' has no attribute 'align'

hi @MJP1998  , i get a erorr module 'pyfoal' has no attribute 'align' . how can i fix this Attribute. thanks you

def get_alignement(text, audio_object):
return pyfoal.align(text, audio_object.get_audio_np_array(), audio_object.get_sample_rate()).json()

**Comment by MJP1998** [comment]
Hi @KalvinThien, Did you check if you have the version of pyfoal I used? pyfoal==0.0.4 (in the requirements.txt)
also check this [page](https://pypi.org/project/pyfoal/0.0.4/) for the installation (you will need HTK)
An update of pyfoal came out a few weeks ago and has no 'align' so I think that's the issue here, I'll make the switch in the future
Hope this helps!

**Comment by KalvinThien** [comment]
Yes, I have installed all modules in requirements.txt
As for HTK, I don't know how to install it on a Windows 10 computer.
Traceback (most recent call last):
   File "d:\tool_tao_video\gui.py", line 127, in generateVideoAI
     ai_content(script_content) # Call the ai_content function with the entered content
   File "d:\tool_tao_video\AI\main.py", line 73, prints ai_content
     video_file_path = video_generator.generate_video(audio_object, video.script, video.title,
   File "d:\tool_creation_video\AI\src\video_generator.py", line 240, in generate_video
     final_clip = self.overlay_subtitles(final_clip, get_alignement(script_without_emojis, audio_object), script,
   File "d:\tool_tao_video\AI\src\video_generator.py", line 55, print get_alignement
     return pyfoal.align(text, audio_object.get_audio_np_array(), audio_object.get_sample_rate()).json()
   File "C:\Users\KalvinThien\AppData\Roaming\Python\Python310\site-packages\pyfoal\core.py", line 56, in align
     return align.aligner(text, audio, duration)
   File "C:\Users\KalvinThien\AppData\Roaming\Python\Python310\site-packages\pyfoal\core.py", line 143, prints __call__
     self.format(directory, audio, script_file)
   File "C:\Users\KalvinThien\AppData\Roaming\Python\Python310\site-packages\pyfoal\core.py", line 200, in format
     subprocess.Popen(
   File "C:\Program Files\Python310\lib\subprocess.py", line 971, prints __init__
     self._execute_child(args, executable, preexec_fn, close_fds,
   File "C:\Program Files\Python310\lib\subprocess.py", line 1456, print _execute_child
     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by MJP1998** [comment]
You can follow [these instructions](https://htk.eng.cam.ac.uk/docs/inst-win.shtml) to install it
